version: '3.4'

services:
  iri.apis.principal:
    container_name: principal.api
    image: iri.apis.principal
    build:
      context: .
      dockerfile: IRI.Apis.Principal/Dockerfile
    ports:
        - 5000:5000
        - 5001:5001

  iri.clients.web:
    container_name: client.angular
    image: iri.clients.web
    build:
      context: .
      dockerfile: IRI.Clients.Web/Dockerfile
      args:
        - "PACKAGE_JSON=iri.clients.web/package.json"
        - "PACKAGE_LOCK_JSON=iri.clients.web/package-lock.json"
    ports:
      - 4200:4200
    volumes:
      - ./iri.clients.web:/project
      - /project/node_modules 
