version: '3.4'

services:
  iri.apis.principal:
    container_name: principal.api
    image: ${DOCKER_REGISTRY-}iriapisprincipal
    build:
      context: .
      dockerfile: IRI.Apis.Principal/Dockerfile
    ports:
        - "5000:5000"
        - "5001:5001"
