version: '3.4'

services:
  iri.clients.web:
    container_name: client.angular
    image: iri.clients.web
    build:
      context: .
      dockerfile: IRI.Clients.Web/Dockerfile
      args:
        - "PACKAGE_JSON=iri.clients.web/package.json"
        - "PACKAGE_LOCK_JSON=iri.clients.web/package-lock.json"
    ports:
      - 4200:4200
    volumes:
      - ./iri.clients.web:/project
      - /project/node_modules 

  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
        ACCEPT_EULA: "Y"
        MSSQL_SA_PASSWORD: "SApA55w0rd2024"
        MSSQL_PID: Developer
    ports:
        - 1:1433 

  iri.apis.rebels.apiweb:
    image: ${DOCKER_REGISTRY-}iriapisrebelsapiweb
    build:
      context: .
      dockerfile: IRI.Apis.Rebels.ApiWeb/Dockerfile
    ports:
        - 5000:5000
        - 5001:5001